### ISSUE TITLE
I got an error  IOError: [Errno 2] No such file or directory: 'molsoc_overlap.dat'

### ISSUE THREAD

**Issue by abbottjlu** [jzpathfinder/pysoc#1]
Traceback (most recent call last):
  File "/home/abbott/composition/pysoc-master/pysoc/bin/soc.py", line 522, in <module>
    s_matr = read_file('molsoc_overlap.dat', 'AO_overlap', nt, 0)
  File "/home/abbott/composition/pysoc-master/pysoc/bin/soc.py", line 40, in read_file
    with open(filein, 'r') as f:
IOError: [Errno 2] No such file or directory: 'molsoc_overlap.dat'
forrtl: No such file or directory

-----------------------------------
Detailed Info
-----------------------------------
abbott@lab-itc:tmp$ which pysoc.py
/home/abbott/composition/pysoc-master/pysoc/bin/pysoc.py
abbott@lab-itc:tmp$ which python
/home/abbott/anaconda2/bin/python
abbott@lab-itc:tmp$ cat /home/abbott/composition/pysoc-master/pysoc/bin/pysoc.py
#!/usr/bin/env python2

''' run soc calculation
'''
import re
import sys
import subprocess
import string
import fileinput

def shell_cmd(cmd):
   out = subprocess.call(cmd, shell=True)
   return out

# where are the soc scripts: soc.py and soc_td
scrip_soc = '/home/abbott/composition/pysoc-master/pysoc/bin'
#scrip_soc = '/fsnfs/users/xinggao/work/gsh/thiothymine/gtsh/test_python/soc_tb/bin'

#please check and set the control parameters in init.py before run pysoc
shell_cmd(scrip_soc+'/soc.py')
shell_cmd(scrip_soc+'/soc_td')

abbott@lab-itc:tmp$ ll /home/abbott/composition/pysoc-master/pysoc/bin
total 844K
-rwxr-xr-x 1 abbott abbott  535 Mar 12 21:48 pysoc.py
-rwxr-xr-x 1 abbott abbott 819K Aug  4  2016 soc_td
-rwxr-xr-x 1 abbott abbott  20K Mar 24  2016 soc.py
abbott@lab-itc:tmp$ ls
gaussian.chk  gaussian.com  gaussian.log  gaussian.rwf  init.py

----------------------
Initial Settings
---------------------
abbott@lab-itc:tmp$ cat init.py
#module called by soc.py
#general control for spin-orbit coupling calculation

import sys
#control parameter
QM_ex_flag = False #False we do QM calculation separately
QM_code = 'gauss_tddft' # gauss_tddft or tddftb
#QM_code = 'tddftb' # gauss_tddft or tddftb
n_s = [1, 2, 3, 4, 5] #default # of excited singlets
n_t = [1, 2, 3, 4, 5] #default # of excited triplets
n_g = ['True']       #default including ground state
soc_scal = 1.0 #scaling factor for Zeff in SOC operator
cicoeff_thresh = [1.0e-5] #thresh hold for ci coeff

# environmental variable
g09root = '/opt/chem/Gaussian/G09.Rev.D.01.SSE42'
#g09root = '/usr/users'
sys.path.append(g09root+'/g09')
#sys.path.append(g09root+'/g09')

##molsoc code from Sandro Giuseppe Chiodo
##with small modifications for input because only the soc
##in atomic basis is needed in the following calculation
molsoc_path = '/home/abbott/composition/pysoc-master/molsoc/bin/molsoc0.1.exe'
#molsoc_path = '/fsnfs/users/xinggao/bin/molsoc/molsoc0.1.exe'

#input files

if QM_code == 'gauss_tddft':
##from Gaussian output
   qm_out = ['gaussian.log', 'gaussian.rwf']
   geom_xyz = []
   soc_key  = ['ANG', 'Zeff', 'DIP']
elif QM_code == 'tddftb':
##from TD-DFTB+ output
   qm_out = ['band.out', 'EXC.DAT', 'oversqr.dat', 'eigenvec.out', \
             'XplusY.DAT', 'SPX.DAT']
   geom_xyz = ['dty.xyz']
   soc_key  = ['ANG', 'Zeff', 'DIP', 'TDB']
dir_para_basis = '/fsnfs/users/xinggao/work/gsh/thiothymine/gtsh/test_python/tddftb/sto2gto/mio-1-1'
##input for molsoc(to be generated)
molsoc_input = ['molsoc.inp', 'molsoc_basis']

##from Newton-X
newton_x = ['geom', 'basis', 'control.dyn']

abbott@lab-itc:tmp$ ll /home/abbott/composition/pysoc-master/molsoc/bin/molsoc0.1.exe
-rwxr-xr-x 1 abbott abbott 1.5M Aug 27  2015 /home/abbott/composition/pysoc-master/molsoc/bin/molsoc0.1.exe

-------------------
Running the code
-------------------
abbott@lab-itc:tmp$ pysoc.py
QM_code gauss_tddft
open file gaussian.log
[[1, 3.4056], [3, 5.6224], [4, 8.0121], [5, 8.1082], [8, 9.7025]]
2 4.1462
['ANG', 'Zeff', 'DIP']
ao_basis [['S', 1], ['SP', 4], ['SP', 4], ['D', 6], ['S', 1], ['SP', 4], ['SP', 4], ['D', 6], ['S', 1], ['S', 1], ['S', 1], ['S', 1]]
n_basis 34
hello1
hello2
open file gaussian.rwf
MOA_coeffs 524R
AO_overlap 514R
XY_coeffs 635R
MOB_coeffs 526R
MO_energy 522R
['0.26622720D+01', '0.29223451D+01', '0.36916501D+01', '0.40570492D+01']
e_s [4.1462, 9.1078, 9.2769, 9.919, 10.4569]
e_t [3.4056, 5.6224, 8.0121, 8.1082, 9.7025]
total order for the roots: [2, 6, 7, 9, 10, 1, 3, 4, 5, 8]
40
['0.20874168D-06', '-0.33377201D-06']
3120 3120
6240
[4.1462, 9.1078, 9.2769, 9.919, 10.4569]
[2, 6, 7, 9, 10]
[3.4056, 5.6224, 8.0121, 8.1082, 9.7025]
[1, 3, 4, 5, 8]
[34, 6, 26]
len(soint) 0
Traceback (most recent call last):
  File "/home/abbott/composition/pysoc-master/pysoc/bin/soc.py", line 522, in <module>
    s_matr = read_file('molsoc_overlap.dat', 'AO_overlap', nt, 0)
  File "/home/abbott/composition/pysoc-master/pysoc/bin/soc.py", line 40, in read_file
    with open(filein, 'r') as f:
IOError: [Errno 2] No such file or directory: 'molsoc_overlap.dat'
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 171, file /home/abbott/composition/pysoc-master/pysoc/tmp/soc_td_input.dat
Image              PC                Routine            Line        Source
soc_td             000000000048B27E  Unknown               Unknown  Unknown
soc_td             0000000000489D16  Unknown               Unknown  Unknown
soc_td             0000000000449EF2  Unknown               Unknown  Unknown
soc_td             000000000041ECCB  Unknown               Unknown  Unknown
soc_td             000000000041E232  Unknown               Unknown  Unknown
soc_td             00000000004287F8  Unknown               Unknown  Unknown
soc_td             000000000040755A  Unknown               Unknown  Unknown
soc_td             00000000004022D9  Unknown               Unknown  Unknown
soc_td             000000000040227C  Unknown               Unknown  Unknown
libc.so.6          00002AD95E2692E1  Unknown               Unknown  Unknown
soc_td             0000000000402179  Unknown               Unknown  Unknown

**Comment by gaox-qd** [comment]
@abbottjlu Please check: 
molsoc_path = '/home/abbott/composition/pysoc-master/molsoc/bin/molsoc0.1.exe'
should be 
molsoc_path = '/home/abbott/composition/pysoc-master/molsoc/molsoc_modified/molsoc0.1/bin/molsoc0.1.exe'
You need to use the my modified version of molsoc.
Hopefully it helps.

**Comment by abbottjlu** [comment]
@jzpathfinder Thanks. Now it works. Thanks.
