### ISSUE TITLE
How to deal with "mo normalization problem, check the MO reading"?

### ISSUE THREAD

**Issue by tzyii** [jzpathfinder/pysoc#3]
I run a g09 job with "# wb97xd/def2svp iop(9/40=4) integral=(ultrafine,acc2e=12) td=(50-50,nstates=10) 6d 10f gfinput nosymm"  options for four molecules, but two of them get "mo normalization problem, check the MO reading" error. Is there some solutions?

**Comment by gaox-qd** [comment]
@tzyii Did you test the examples? How about using "# wb97xd/def2svp td=(50-50,nstates=10) 6d 10f gfinput nosymm"?

**Comment by tzyii** [comment]
@jzpathfinder Solved. The reason is most likely the incorrect process of atomic positions. For the failure cases, the coordinates in gaussian input is "C     -1     5.039121448    -0.455762720     6.086155550", where the second number represent that the atom is fixed. But the pysoc treat it as x component of coordinate. In molsoc.inp, the coordinate is "C          -1.00000        5.03912       -0.45576".
Thank you!
